import { Activity, MoodEntry, QuoteOfTheDay, CommunityPost, Session, Product, Challenge, Notification, Comment } from '../types';
import { supabase } from './supabaseClient';

export let MOCK_ACTIVITIES: Activity[] = [
  {
    id: 'eft-anxiete',
    type: 'mental',
    categorie: 'EFT',
    titre: 'Libération de l\'Anxiété',
    description: 'Une séance complète pour identifier votre niveau d\'anxiété sur une échelle de 0 à 10 et pratiquer la ronde EFT (point karaté, sommet de la tête, sourcils) pour retrouver un calme profond.',
    dureeMinutes: 10,
    imageUrl: 'https://images.unsplash.com/photo-1474418397713-7ede21d49118?q=80&w=800&auto=format&fit=crop',
    couleurPrincipale: '#ec9b7b',
    tags: ['Anxiété', 'Sérénité', 'Ronde complète'],
    contentUrl: 'https://www.youtube.com/watch?v=P-A_SUnU88I',
    estFavori: false,
    ingredients: [],
    instructions: [],
  },
  {
    id: 'eft-humeur',
    type: 'mental',
    categorie: 'EFT',
    titre: 'Sortir de la Morosité',
    description: 'Idéal pour les jours de grisaille ou de baisse de moral. Cette ronde EFT vous aide à transformer une humeur maussade en une énergie plus légère et positive.',
    dureeMinutes: 8,
    imageUrl: 'https://images.unsplash.com/photo-1499209974431-9dddcece7f88?q=80&w=800&auto=format&fit=crop',
    couleurPrincipale: '#f5e380',
    tags: ['Humeur', 'Hiver', 'Énergie'],
    contentUrl: 'https://www.youtube.com/embed/V8E0w_C7Jb8',
    estFavori: true,
    ingredients: [],
    instructions: [],
  },
  {
    id: 'eft-menopause',
    type: 'mental',
    categorie: 'EFT',
    titre: 'Confort & Ménopause',
    description: 'Séance ciblée sur les douleurs articulaires liées à la ménopause. Travaillez sur les mains, les épaules et les hanches pour atténuer l\'inconfort physique par le tapotement.',
    dureeMinutes: 12,
    imageUrl: 'https://images.unsplash.com/photo-1544367563-12123d8965cd?q=80&w=800&auto=format&fit=crop',
    couleurPrincipale: '#a5cdbc',
    tags: ['Ménopause', 'Douleurs', 'Corps'],
    contentUrl: 'https://www.youtube.com/embed/Y0rQzV8S09w',
    estFavori: false,
    ingredients: [],
    instructions: [],
  },
  {
    id: 'eft-choix',
    type: 'mental',
    categorie: 'EFT',
    titre: 'Le Pouvoir du Choix',
    description: 'Une pratique avancée pour décider consciemment de se libérer d\'une peur persistante. Transformez vos doutes en une affirmation de confiance totale en la vie.',
    dureeMinutes: 15,
    imageUrl: 'https://images.unsplash.com/photo-1493836512294-502baa1986e2?q=80&w=800&auto=format&fit=crop',
    couleurPrincipale: '#ec9b7b',
    tags: ['Choix', 'Confiance', 'Libération'],
    contentUrl: 'https://www.youtube.com/embed/mG_mK7Fp6yA',
    estFavori: false,
    ingredients: [],
    instructions: [],
  },
  {
    id: 'm1',
    type: 'mental',
    categorie: 'Méditation',
    titre: 'Méditation Atmosphère',
    description: 'Une séance guidée pour se reconnecter à son environnement et trouver le calme intérieur. Idéal pour commencer la journée avec sérénité.',
    dureeMinutes: 10,
    imageUrl: 'https://images.unsplash.com/photo-1499209974431-9dddcece7f88?q=80&w=800&auto=format&fit=crop',
    couleurPrincipale: '#ec9b7b',
    tags: ['Calme', 'Débutant', 'Matin'],
    contentUrl: '',
    estFavori: false,
    ingredients: [],
    instructions: [],
  },
  {
    id: 'm2',
    type: 'mental',
    categorie: 'Sophrologie',
    titre: 'Détente corporelle',
    description: 'Relâchez les tensions musculaires une par une avec cette méthode douce. Parfait après une journée de travail assis.',
    dureeMinutes: 15,
    imageUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?q=80&w=800&auto=format&fit=crop',
    couleurPrincipale: '#a5cdbc',
    tags: ['Stress', 'Corps', 'Soir'],
    contentUrl: '',
    estFavori: true,
    ingredients: [],
    instructions: [],
  },
  {
    id: 'm3',
    type: 'mental',
    categorie: 'Sommeil',
    titre: 'Voyage onirique',
    description: 'Une histoire douce pour glisser vers le sommeil sans effort. Laissez-vous porter par la voix et la musique.',
    dureeMinutes: 20,
    imageUrl: 'https://images.unsplash.com/photo-1519681393798-3828fb4090bb?q=80&w=800&auto=format&fit=crop',
    couleurPrincipale: '#615245',
    tags: ['Nuit', 'Hypnose', 'Sommeil'],
    contentUrl: '',
    estFavori: false,
    ingredients: [],
    instructions: [],
  },
  {
    id: 'm4',
    type: 'mental',
    categorie: 'Respiration',
    titre: 'Cohérence cardiaque',
    description: '5 minutes pour réguler votre rythme cardiaque et apaiser l\'anxiété. À pratiquer 3 fois par jour pour un effet optimal.',
    dureeMinutes: 5,
    imageUrl: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?q=80&w=800&auto=format&fit=crop',
    couleurPrincipale: '#ec9b7b',
    tags: ['Anxiété', 'Rapide', 'SOS'],
    contentUrl: '',
    estFavori: false,
    ingredients: [],
    instructions: [],
  },
  {
    id: 'm5',
    type: 'mental',
    categorie: 'Méditation',
    titre: 'Marche en forêt',
    description: 'Immersion sonore au cœur de la nature pour une pause régénérante au bureau. Fermez les yeux et évadez-vous.',
    dureeMinutes: 8,
    imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=800&auto=format&fit=crop',
    couleurPrincipale: '#2d6a4f',
    tags: ['Nature', 'Audio', 'Pause'],
    contentUrl: '',
    estFavori: false,
    ingredients: [],
    instructions: [],
  },
  {
    id: 'm6',
    type: 'mental',
    categorie: 'Relaxation',
    titre: 'Bruit Blanc & Pluie',
    description: 'Le son apaisant de la pluie pour favoriser la concentration ou la sieste. Boucle parfaite sans coupure.',
    dureeMinutes: 30,
    imageUrl: 'https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?q=80&w=800&auto=format&fit=crop',
    couleurPrincipale: '#4a6fa5',
    tags: ['Focus', 'Audio', 'Long'],
    contentUrl: '',
    estFavori: false,
    ingredients: [],
    instructions: [],
  },
  {
    id: 'm7',
    type: 'mental',
    categorie: 'Sophrologie',
    titre: 'Visualisation Positive',
    description: 'Préparez votre mental à réussir votre journée ou un événement important grâce à la visualisation.',
    dureeMinutes: 12,
    imageUrl: 'https://images.unsplash.com/photo-1493836512294-502baa1986e2?q=80&w=800&auto=format&fit=crop',
    couleurPrincipale: '#f5e380',
    tags: ['Confiance', 'Matin', 'Mental'],
    contentUrl: '',
    estFavori: true,
    ingredients: [],
    instructions: [],
  },
  {
    id: 'm8',
    type: 'mental',
    categorie: 'Respiration',
    titre: 'Respiration 4-7-8',
    description: 'La technique du Dr. Weil pour s\'endormir en moins de 60 secondes. Inspirez, retenez, expirez.',
    dureeMinutes: 3,
    imageUrl: 'https://images.unsplash.com/photo-1520206183501-b80df610434f?q=80&w=800&auto=format&fit=crop',
    couleurPrincipale: '#a5cdbc',
    tags: ['Sommeil', 'Technique', 'Rapide'],
    contentUrl: '',
    estFavori: false,
    ingredients: [],
    instructions: [],
  },
  {
    id: 'm9',
    type: 'mental',
    categorie: 'Méditation',
    titre: 'Scan Corporel',
    description: 'Prenez conscience de chaque partie de votre corps pour une relaxation totale.',
    dureeMinutes: 25,
    imageUrl: 'https://images.unsplash.com/photo-1544367563-12123d8965cd?q=80&w=800&auto=format&fit=crop',
    couleurPrincipale: '#cce1b0',
    tags: ['Corps', 'Détente', 'Long'],
    contentUrl: '',
    estFavori: false,
    ingredients: [],
    instructions: [],
  },
  {
    id: 'm10',
    type: 'mental',
    categorie: 'Relaxation',
    titre: 'Sons des Vagues',
    description: 'Le rythme régulier de l\'océan pour calmer l\'esprit instantanément.',
    dureeMinutes: 45,
    imageUrl: 'https://images.unsplash.com/photo-1505118380757-91f5f5632de0?q=80&w=800&auto=format&fit=crop',
    couleurPrincipale: '#4a6fa5',
    tags: ['Nature', 'Sommeil', 'Audio'],
    contentUrl: '',
    estFavori: false,
    ingredients: [],
    instructions: [],
  },
  {
    id: 'm11',
    type: 'mental',
    categorie: 'Sophrologie',
    titre: 'Bulle de Protection',
    description: 'Créez une bulle imaginaire pour vous protéger du stress extérieur.',
    dureeMinutes: 8,
    imageUrl: 'https://images.unsplash.com/photo-1506259091721-347f798196d4?q=80&w=800&auto=format&fit=crop',
    couleurPrincipale: '#e94a38',
    tags: ['Stress', 'Protection', 'Visualisation'],
    contentUrl: '',
    estFavori: false,
    ingredients: [],
    instructions: [],
  },
  {
    id: 'm12',
    type: 'mental',
    categorie: 'Respiration',
    titre: 'Respiration Carrée',
    description: 'Une technique militaire pour retrouver son calme en situation de stress intense.',
    dureeMinutes: 4,
    imageUrl: 'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?q=80&w=800&auto=format&fit=crop',
    couleurPrincipale: '#373a37',
    tags: ['Focus', 'Stress', 'Technique'],
    contentUrl: '',
    estFavori: false,
    ingredients: [],
    instructions: [],
  },
  {
    id: 'm13',
    type: 'mental',
    categorie: 'Méditation',
    titre: 'Méditation du Soir',
    description: 'Une longue méditation pour clore la journée.',
    dureeMinutes: 25,
    imageUrl: 'https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?q=80&w=800&auto=format&fit=crop',
    couleurPrincipale: '#615245',
    tags: ['Soir', 'Long', 'Calme'],
    contentUrl: '',
    estFavori: false,
    ingredients: [],
    instructions: [],
  },
  {
    id: 'm14',
    type: 'mental',
    categorie: 'Confiance',
    titre: 'Affirmations du Matin',
    description: 'Boostez votre estime de vous en 5 minutes.',
    dureeMinutes: 5,
    imageUrl: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?q=80&w=800&auto=format&fit=crop',
    couleurPrincipale: '#f5e380',
    tags: ['Matin', 'Rapide', 'Confiance'],
    contentUrl: '',
    estFavori: false,
    ingredients: [],
    instructions: [],
  },
  {
    id: 'p1',
    type: 'physique',
    categorie: 'Yoga',
    titre: 'Salutation au Soleil Douce',
    description: 'Réveillez votre corps en douceur avec ce flow matinal accessible à tous. Idéal pour dérouiller les articulations.',
    dureeMinutes: 12,
    imageUrl: 'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?q=80&w=800&auto=format&fit=crop',
    couleurPrincipale: '#f5e380',
    tags: ['Matin', 'Souplesse', 'Energie'],
    contentUrl: 'https://www.youtube.com/embed/v7AYKMP6rOE',
    estFavori: false,
    ingredients: [],
    instructions: [],
  },
  {
    id: 'p2',
    type: 'physique',
    categorie: 'Recettes',
    titre: 'Bowl Vert Vitalité',
    description: 'Un mélange croquant de légumes verts, avocat et quinoa pour le déjeuner. Plein de nutriments essentiels.',
    dureeMinutes: 20,
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=800&auto=format&fit=crop',
    couleurPrincipale: '#e94a38',
    tags: ['Déjeuner', 'Healthy', 'Végétarien'],
    contentUrl: '',
    estFavori: true,
    ingredients: ['Avocat', 'Quinoa', 'Epinards', 'Citron'],
    instructions: ['1/ Cuire le quinoa', '2/ Couper les légumes', '3/ Tout mélanger'],
  },
  {
    id: 'p3',
    type: 'physique',
    categorie: 'Activité physique',
    titre: 'Marche consciente',
    description: 'Guide audio pour une marche active et méditative en extérieur. Reconnectez-vous à vos sens.',
    dureeMinutes: 30,
    imageUrl: 'https://images.unsplash.com/photo-1552674605-46d536d2e681?q=80&w=800&auto=format&fit=crop',
    couleurPrincipale: '#cce1b0',
    tags: ['Extérieur', 'Cardio doux', 'Nature'],
    contentUrl: '',
    estFavori: false,
    ingredients: [],
    instructions: [],
  },
  {
    id: 'p4',
    type: 'physique',
    categorie: 'Activité physique',
    titre: 'Renforcement Pilates',
    description: 'Tonifiez votre sangle abdominale sans impact grâce à ces mouvements précis.',
    dureeMinutes: 25,
    imageUrl: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?q=80&w=800&auto=format&fit=crop',
    couleurPrincipale: '#cce1b0',
    tags: ['Force', 'Maison', 'Abdos'],
    contentUrl: '',
    estFavori: false,
    ingredients: [],
    instructions: [],
  },
  {
    id: 'p5',
    type: 'physique',
    categorie: 'Activité physique',
    titre: 'Renforcement Musculaire Complet',
    description: 'Une séance intense pour travailler tout le corps sans matériel. Préparez-vous à transpirer !',
    dureeMinutes: 45,
    imageUrl: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?q=80&w=800&auto=format&fit=crop',
    couleurPrincipale: '#cce1b0',
    tags: ['Force', 'Complet', 'Intense'],
    contentUrl: 'https://www.youtube.com/embed/v7AYKMP6rOE',
    estFavori: false,
    ingredients: [],
    instructions: [],
  },
  {
    id: 'p6',
    type: 'physique',
    categorie: 'Yoga',
    titre: 'Yoga du Soir',
    description: 'Étirements profonds pour relâcher la pression de la journée et mieux dormir.',
    dureeMinutes: 20,
    imageUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?q=80&w=800&auto=format&fit=crop',
    couleurPrincipale: '#615245',
    tags: ['Soir', 'Détente', 'Sommeil'],
    contentUrl: '',
    estFavori: true,
    ingredients: [],
    instructions: [],
  },
  {
    id: 'p7',
    type: 'physique',
    categorie: 'Recettes',
    titre: 'Smoothie Énergie',
    description: 'Un boost de vitamines immédiat avec banane, épinard et gingembre.',
    dureeMinutes: 5,
    imageUrl: 'https://images.unsplash.com/photo-1610970881699-44a5587cabec?q=80&w=800&auto=format&fit=crop',
    couleurPrincipale: '#cce1b0',
    tags: ['Boisson', 'Végétarien', 'Rapide'],
    contentUrl: '',
    estFavori: false,
    ingredients: ['Banane', 'Epinard', 'Lait végétal', 'Gingembre'],
    instructions: ['1/ Mixer tous les ingrédients', '2/ Servir frais'],
  },
  {
    id: 'p8',
    type: 'physique',
    categorie: 'Activité physique',
    titre: 'HIIT Express',
    description: '15 minutes à haute intensité pour brûler des calories rapidement.',
    dureeMinutes: 15,
    imageUrl: 'https://images.unsplash.com/photo-1601422407692-ec4eeec1d9b3?q=80&w=800&auto=format&fit=crop',
    couleurPrincipale: '#e94a38',
    tags: ['Cardio', 'Intense', 'Sans matériel'],
    contentUrl: '',
    estFavori: false,
    ingredients: [],
    instructions: [],
  },
  {
    id: 'p9',
    type: 'physique',
    categorie: 'Activité physique',
    titre: 'Stretching du Dos',
    description: 'Soulagez les douleurs dorsales liées au télétravail.',
    dureeMinutes: 10,
    imageUrl: 'https://images.unsplash.com/photo-1544367563-12123d8965cd?q=80&w=800&auto=format&fit=crop',
    couleurPrincipale: '#a5cdbc',
    tags: ['Dos', 'Santé', 'Bureau'],
    contentUrl: '',
    estFavori: false,
    ingredients: [],
    instructions: [],
  },
  {
    id: 'p10',
    type: 'physique',
    categorie: 'Recettes',
    titre: 'Porridge Protéiné',
    description: 'Un petit-déjeuner complet pour tenir toute la matinée sans fringale.',
    dureeMinutes: 10,
    imageUrl: 'https://images.unsplash.com/photo-1517673132405-a56a62b18caf?q=80&w=800&auto=format&fit=crop',
    couleurPrincipale: '#f5e380',
    tags: ['Petit-déjeuner', 'Protéine', 'Chaud'],
    contentUrl: '',
    estFavori: false,
    ingredients: ['Avoine', 'Lait', 'Protéine en poudre', 'Fruits rouges'],
    instructions: ['1/ Chauffer le lait', '2/ Ajouter l\'avoine', '3/ Mélanger la protéine', '4/ Garnir'],
  },
  {
    id: 'p11',
    type: 'physique',
    categorie: 'Yoga',
    titre: 'Équilibre et Ancrage',
    description: 'Travaillez vos postures d\'équilibre pour renforcer les chevilles et la concentration.',
    dureeMinutes: 18,
    imageUrl: 'https://images.unsplash.com/photo-1552196563-55cd4e45efb3?q=80&w=800&auto=format&fit=crop',
    couleurPrincipale: '#ec9b7b',
    tags: ['Equilibre', 'Focus', 'Jambes'],
    contentUrl: '',
    estFavori: false,
    ingredients: [],
    instructions: [],
  },
  {
    id: 'p12',
    type: 'physique',
    categorie: 'Activité physique',
    titre: 'Tabata Cardio',
    description: '4 minutes d\'effort intense pour booster le métabolisme.',
    dureeMinutes: 4,
    imageUrl: 'https://images.unsplash.com/photo-1599058945522-28d584b6f0ff?q=80&w=800&auto=format&fit=crop',
    couleurPrincipale: '#e94a38',
    tags: ['Cardio', 'Express', 'Intense'],
    contentUrl: '',
    estFavori: false,
    ingredients: [],
    instructions: [],
  },
  {
    id: 'p13',
    type: 'physique',
    categorie: 'Activité physique',
    titre: 'Musculation Bras',
    description: 'Séance ciblée biceps et triceps avec poids.',
    dureeMinutes: 30,
    imageUrl: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?q=80&w=800&auto=format&fit=crop',
    couleurPrincipale: '#373a37',
    tags: ['Force', 'Bras', 'Poids'],
    contentUrl: '',
    estFavori: false,
    ingredients: [],
    instructions: [],
  },
  {
    id: 'p14',
    type: 'physique',
    categorie: 'Activité physique',
    titre: 'Musculation Avancée',
    description: 'Séance full body très intense.',
    dureeMinutes: 50,
    imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=800&auto=format&fit=crop',
    couleurPrincipale: '#e94a38',
    tags: ['Force', 'Intense'],
    contentUrl: '',
    estFavori: false,
    ingredients: [],
    instructions: [],
  },
  {
    id: 'm15',
    type: 'mental',
    categorie: 'Sophrologie',
    titre: 'Détente corporelle',
    description: 'Relâchez les tensions musculaires 1er degré',
    dureeMinutes: 15,
    imageUrl: 'https://lh3.googleusercontent.com/d/1k03K6PzoWP3qMC4PTcNHkixEyolPz6jN',
    couleurPrincipale: '#a5cdbc',
    tags: ['Dos', 'Santé', 'Détente'],
    contentUrl: '',
    estFavori: false,
    ingredients: [],
    instructions: [],
  },
  {
    id: 'm16',
    type: 'mental',
    categorie: 'Sophrologie',
    titre: 'Détente corporelle',
    description: 'Relâchez les tensions musculaires 2ième degré',
    dureeMinutes: 15,
    imageUrl: 'https://lh3.googleusercontent.com/d/1sYHlYxGoIS5YAVZ4hQXhuuwGOE_-yyNO',
    couleurPrincipale: '#a5cdbc',
    tags: ['Dos', 'Santé', 'Détente'],
    contentUrl: '',
    estFavori: false,
    ingredients: [],
    instructions: [],
  },
  {
    id: 'm17',
    type: 'mental',
    categorie: 'Sophrologie',
    titre: 'Détente corporelle',
    description: 'Relâchez les tensions musculaires 3ième degré',
    dureeMinutes: 15,
    imageUrl: 'https://lh3.googleusercontent.com/d/1H24cALcBRFrFnxPNZSy0tER_NRySvWB2',
    couleurPrincipale: '#a5cdbc',
    tags: ['Dos', 'Santé', 'Détente'],
    contentUrl: '',
    estFavori: false,
    ingredients: [],
    instructions: [],
  },
  {
    id: 'm18',
    type: 'mental',
    categorie: 'Sophrologie',
    titre: 'Détente corporelle',
    description: 'Relâchez les tensions musculaires 4ième degré',
    dureeMinutes: 15,
    imageUrl: 'https://lh3.googleusercontent.com/d/1MK5oDsDAODgjQE1C2-ldk9rmzWQzxm-2',
    couleurPrincipale: '#a5cdbc',
    tags: ['Dos', 'Santé', 'Détente'],
    contentUrl: '',
    estFavori: false,
    ingredients: [],
    instructions: [],
  },
  {
    id: 'm19',
    type: 'mental',
    categorie: 'Sophrologie',
    titre: 'Détente corporelle',
    description: 'Relâchez les tensions musculaires Trac tac (anciennement RDC1)',
    dureeMinutes: 15,
    imageUrl: 'https://lh3.googleusercontent.com/d/1_E2bVHkp48GS8vzf7ZWCb8CVC3DSYS9y',
    couleurPrincipale: '#a5cdbc',
    tags: ['Dos', 'Santé', 'Détente'],
    contentUrl: '',
    estFavori: false,
    ingredients: [],
    instructions: [],
  },
  {
    id: 'p15',
    type: 'physique',
    categorie: 'Recettes',
    titre: 'Salade colorée de couleur d\'automne',
    description: 'Une explosion de couleurs et de textures avec des légumes crus croquants, de l\'avocat fondant et des pois chiches rassasiants',
    dureeMinutes: 20,
    imageUrl: 'https://lh3.googleusercontent.com/d/1WSTn0qyO1m5c9J0QpqfNvQrkL55NW9UZ',
    couleurPrincipale: '#e94a38',
    tags: ['Déjeuner', 'Diététique', 'Santé'],
    contentUrl: '',
    estFavori: false,
    ingredients: ['Quelques feuilles de salade verte', 'Radis noir', 'Concombre', 'Tomates cerises', 'Avocat', 'Poivron jaune', 'Oignon rouge', 'Féta', 'Pois chiches', 'Basilic frais', 'Filet de jus de citron et d’huile d’olive'],
    instructions: [],
  },
  {
    id: 'p16',
    type: 'physique',
    categorie: 'Recettes',
    titre: 'Salade méditerranéenne',
    description: 'Une salade généreuse et complète où le riz et les sardines s\'allient pour un plein d\'énergie et de bons acides gras',
    dureeMinutes: 20,
    imageUrl: 'https://lh3.googleusercontent.com/d/1lvJvJOF-IES-U-54_WqL37PNfXOa3HCo',
    couleurPrincipale: '#e94a38',
    tags: ['Déjeuner', 'Diététique', 'Santé'],
    contentUrl: '',
    estFavori: false,
    ingredients: ['1 verre de riz', '1 avocat', 'la moitié d’une petite boîte de maïs', '1 grosse tomate ou 2 petites', '1 boîte de sardines', '1 oeuf dur', 'Quelques olives noires', 'La moitié d’un poivron rouge', '½ oignon rouge', 'Des graines de courge'],
    instructions: [],
  },
  {
    id: 'p17',
    type: 'physique',
    categorie: 'Recettes',
    titre: 'Salade lentilles tofu',
    description: 'Un duo végétarien puissant de lentilles fondantes et de tofu mariné pour un repas complet',
    dureeMinutes: 20,
    imageUrl: 'https://lh3.googleusercontent.com/d/16wVyC-vFGW0YVKWJzJmjiBIbm4N-vb1a',
    couleurPrincipale: '#e94a38',
    tags: ['Déjeuner', 'Diététique', 'Santé'],
    contentUrl: '',
    estFavori: false,
    ingredients: ['2 verres de lentilles', '1 boîte de tomates concassées', '1 concombre', '2 échalotes', 'Dés de tofu au basilic', 'Graines de lentilles', 'Copeaux de parmesan', 'Dés de féta'],
    instructions: [],
  },
  {
    id: 'p18',
    type: 'physique',
    categorie: 'Recettes',
    titre: 'Salade fraîcheur',
    description: 'Un mélange ultra-frais et détox où le croquant de l\'endive et du poivron vert rencontre l\'acidité d\'une pomme. Les pignons de pin apportent une touche boisée et délicate',
    dureeMinutes: 20,
    imageUrl: 'https://lh3.googleusercontent.com/d/1lQkpBF1yFgxpsmT1ei4S0PCD-uq7G8Qs',
    couleurPrincipale: '#e94a38',
    tags: ['Déjeuner', 'Diététique', 'Santé'],
    contentUrl: '',
    estFavori: false,
    ingredients: ['½ concombre', '½ poivron vert', '1 échalote', 'la moitié d’une pomme granny smith', 'quelques pignons de pin', '2 endives'],
    instructions: [],
  },
  {
    id: 'p19',
    type: 'physique',
    categorie: 'Recettes',
    titre: 'Salade d\'été',
    description: 'Une assiette lumineuse alliant le crémeux de l\'avocat et de la féta au croquant des poivrons jaunes',
    dureeMinutes: 20,
    imageUrl: 'https://lh3.googleusercontent.com/d/1eIaLBXgdxmORr-19z-ZLAHWWovX1vvsR',
    couleurPrincipale: '#e94a38',
    tags: ['Déjeuner', 'Diététique', 'Santé'],
    contentUrl: '',
    estFavori: false,
    ingredients: ['½ poivron jaune', '2 tomates', 'Quelques dés de féta', 'La moitié d’un avocat', 'Sel Gomasio', '½ concombre', 'Un filet d’huile d’olive', 'Un jus de citron'],
    instructions: [],
  },
  {
    id: 'm20',
    type: 'mental',
    categorie: 'Respiration',
    titre: 'Respiration ballon',
    description: 'Respiration 2-8-4',
    dureeMinutes: 5,
    imageUrl: 'https://lh3.googleusercontent.com/d/1mhhTwEEmgb_CjZ6-PYmMUQn9IUaU0lBT',
    couleurPrincipale: '#a5cdbc',
    tags: ['Respiration', 'Détente', 'Sommeil'],
    contentUrl: 'https://www.youtube.com/watch?v=zRHEExheci0',
    estFavori: false,
    ingredients: [],
    instructions: [],
  },
  {
    id: 'm21',
    type: 'mental',
    categorie: 'Respiration',
    titre: 'Respiration ballon',
    description: 'Respiration 4-2-4-2',
    dureeMinutes: 5,
    imageUrl: 'https://lh3.googleusercontent.com/d/1mhhTwEEmgb_CjZ6-PYmMUQn9IUaU0lBT',
    couleurPrincipale: '#a5cdbc',
    tags: ['Respiration', 'Détente', 'Sommeil'],
    contentUrl: 'https://www.youtube.com/watch?v=bgn563YyhPo',
    estFavori: false,
    ingredients: [],
    instructions: [],
  },
  {
    id: 'm22',
    type: 'mental',
    categorie: 'Respiration',
    titre: 'Respiration ballon',
    description: 'Respiration 3-2-6-2',
    dureeMinutes: 5,
    imageUrl: 'https://lh3.googleusercontent.com/d/1mhhTwEEmgb_CjZ6-PYmMUQn9IUaU0lBT',
    couleurPrincipale: '#a5cdbc',
    tags: ['Respiration', 'Détente', 'Sommeil'],
    contentUrl: 'https://www.youtube.com/watch?v=sgchBQRe4ZE',
    estFavori: false,
    ingredients: [],
    instructions: [],
  },
  {
    id: 'm23',
    type: 'mental',
    categorie: 'Respiration',
    titre: 'Respiration ballon',
    description: 'Respiration 4-4-6-2',
    dureeMinutes: 5,
    imageUrl: 'https://lh3.googleusercontent.com/d/1mhhTwEEmgb_CjZ6-PYmMUQn9IUaU0lBT',
    couleurPrincipale: '#a5cdbc',
    tags: ['Respiration', 'Détente', 'Sommeil'],
    contentUrl: 'https://www.youtube.com/watch?v=YEiwsMA8rGE',
    estFavori: false,
    ingredients: [],
    instructions: [],
  },
  {
    id: 'm24',
    type: 'mental',
    categorie: 'Respiration',
    titre: 'Respiration ballon',
    description: 'Respiration 4-6',
    dureeMinutes: 5,
    imageUrl: 'https://lh3.googleusercontent.com/d/1mhhTwEEmgb_CjZ6-PYmMUQn9IUaU0lBT',
    couleurPrincipale: '#a5cdbc',
    tags: ['Respiration', 'Détente', 'Sommeil'],
    contentUrl: 'https://www.youtube.com/watch?v=_uFAhSy4Uts',
    estFavori: false,
    ingredients: [],
    instructions: [],
  },
  {
    id: 'm25',
    type: 'mental',
    categorie: 'Respiration',
    titre: 'Respiration ballon',
    description: 'Respiration 4-7-8',
    dureeMinutes: 5,
    imageUrl: 'https://lh3.googleusercontent.com/d/1mhhTwEEmgb_CjZ6-PYmMUQn9IUaU0lBT',
    couleurPrincipale: '#a5cdbc',
    tags: ['Respiration', 'Détente', 'Sommeil'],
    contentUrl: 'https://www.youtube.com/watch?v=6djmjoYHv0A',
    estFavori: false,
    ingredients: [],
    instructions: [],
  },
  {
    id: 'm26',
    type: 'mental',
    categorie: 'Respiration',
    titre: 'Respiration ballon',
    description: 'Respiration 5-5',
    dureeMinutes: 5,
    imageUrl: 'https://lh3.googleusercontent.com/d/1mhhTwEEmgb_CjZ6-PYmMUQn9IUaU0lBT',
    couleurPrincipale: '#a5cdbc',
    tags: ['Respiration', 'Détente', 'Sommeil'],
    contentUrl: 'https://www.youtube.com/watch?v=xGN3h2FLQA4',
    estFavori: false,
    ingredients: [],
    instructions: [],
  },
];

export let MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod1',
    name: 'Tapis de Yoga Confort',
    price: 45,
    image_url: '',
    category: 'Accessoires',
    description: 'Tapis épais (6mm) et antidérapant en TPE écologique. Idéal pour vos séances de yoga et pilates à la maison.',
  },
  {
    id: 'prod2',
    name: 'Gourde Isotherme Lyloo',
    price: 25,
    image_url: '',
    category: 'Lifestyle',
    description: 'Gardez votre eau fraîche pendant 24h et votre tisane chaude 12h. Acier inoxydable.',
  },
  {
    id: 'prod3',
    name: 'Zafu de Méditation',
    price: 35,
    image_url: '',
    category: 'Méditation',
    description: 'Coussin de méditation ergonomique en coton bio, garnissage épeautre. Pour une posture parfaite.',
  },
  {
    id: 'prod4',
    name: 'Huile Essentielle Lavande',
    price: 12,
    image_url: '',
    category: 'Aromathérapie',
    description: 'Lavande vraie bio. Idéale pour la relaxation et favoriser l\'endormissement.',
  },
  {
    id: 'prod5',
    name: 'Briques de Yoga (Lot de 2)',
    price: 22,
    image_url: '',
    category: 'Accessoires',
    description: 'Briques en liège naturel pour vous aider dans vos postures d\'équilibre et de souplesse.',
  },
  {
    id: 'prod6',
    name: 'Diffuseur Ultrasonique',
    price: 39,
    image_url: '',
    category: 'Aromathérapie',
    description: 'Diffuseur d\'huiles essentielles silencieux avec lumière d\'ambiance douce.',
  },
  {
    id: 'prod7',
    name: 'Journal de Gratitude',
    price: 18,
    image_url: '',
    category: 'Papeterie',
    description: 'Carnet guidé pour noter vos pensées positives chaque jour. Couverture rigide recyclée.',
  },
  {
    id: 'prod8',
    name: 'Infusion "Nuit Calme"',
    price: 9.5,
    image_url: '',
    category: 'Nutrition',
    description: 'Mélange de mélisse, verveine et tilleul. 100g vrac bio.',
  },
];

export let MOCK_SESSIONS: Session[] = [
  {
    id: 's1',
    activityId: 'm1',
    date: new Date().toISOString(),
    duration: 0,
    moodBefore: '',
    moodAfter: '',
    note: '',
    userId: 'user_123',
    statut: 'terminee',
  },
  {
    id: 's2',
    activityId: 'p1',
    date: new Date().toISOString(),
    duration: 0,
    moodBefore: '',
    moodAfter: '',
    note: '',
    userId: 'user_123',
    statut: 'terminee',
  },
  {
    id: 's3',
    activityId: 'm2',
    date: new Date().toISOString(),
    duration: 0,
    moodBefore: '',
    moodAfter: '',
    note: '',
    userId: 'user_123',
    statut: 'terminee',
  },
  {
    id: 's4',
    activityId: 'm3',
    date: new Date().toISOString(),
    duration: 0,
    moodBefore: '',
    moodAfter: '',
    note: '',
    userId: 'user_123',
    statut: 'terminee',
  },
  {
    id: 's5',
    activityId: 'p3',
    date: new Date().toISOString(),
    duration: 0,
    moodBefore: '',
    moodAfter: '',
    note: '',
    userId: 'user_123',
    statut: 'terminee',
  },
  {
    id: 's6',
    activityId: 'p6',
    date: new Date().toISOString(),
    duration: 0,
    moodBefore: '',
    moodAfter: '',
    note: '',
    userId: 'user_123',
    statut: 'terminee',
  },
];

export let MOCK_CHALLENGES: Challenge[] = [
  {
    id: 'c1',
    title: '',
    description: 'Chaque jour, notez 3 choses pour lesquelles vous êtes reconnaissant.',
    durationDays: 0,
    startDate: new Date().toISOString(),
    isJoined: true,
    participants: 1240,
    image_url: '',
  },
  {
    id: 'c2',
    title: '',
    description: 'Boire 2L d\'eau par jour pendant 2 semaines. Votre peau vous remerciera !',
    durationDays: 0,
    startDate: new Date().toISOString(),
    isJoined: false,
    participants: 856,
    image_url: '',
  },
  {
    id: 'c3',
    title: '',
    description: 'Aucun écran 1h avant de dormir pendant 5 jours. Retrouvez un sommeil réparateur.',
    durationDays: 0,
    startDate: new Date().toISOString(),
    isJoined: false,
    participants: 2300,
    image_url: '',
  },
  {
    id: 'c4',
    title: '',
    description: '10 000 pas par jour pendant 1 mois. Bougez plus, vivez mieux.',
    durationDays: 0,
    startDate: new Date().toISOString(),
    isJoined: false,
    participants: 560,
    image_url: '',
  },
];

export let MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'n1',
    type: 'community',
    message: 'Rejoignez le défi "Sommeil Réparateur" dès aujourd\'hui.',
    date: new Date().toISOString(),
    read: false,
    title: 'Notification système',
  },
  {
    id: 'n2',
    type: 'wellness',
    message: 'Vous avez complété 3 séances cette semaine.',
    date: new Date().toISOString(),
    read: true,
    title: 'Notification système',
  },
  {
    id: 'n3',
    type: 'community',
    message: '"Le rituel du matin..."',
    date: new Date().toISOString(),
    read: false,
    title: 'Notification système',
  },
  {
    id: 'n4',
    type: 'system',
    message: 'Prenez 5 minutes pour respirer avant de dormir.',
    date: new Date().toISOString(),
    read: true,
    title: 'Notification système',
  },
];

export let MOCK_MOOD_HISTORY: MoodEntry[] = [
];

export let MOCK_QUOTES: QuoteOfTheDay[] = [
];

export let MOCK_POSTS: CommunityPost[] = [
  {
    id: '1',
    author: 'Sophie',
    date: new Date().toISOString(),
    content: 'Le rituel du matin a changé ma journée ! Je me sens tellement plus apaisée.',
    likes: 12,
    type: 'message',
    reactions: {},
    comments: [
    ],
  },
  {
    id: '2',
    author: 'Équipe LYLOO',
    date: new Date().toISOString(),
    content: 'Conseil du jour : Prenez le temps de mâcher chaque bouchée pour une meilleure digestion.',
    likes: 45,
    type: 'message',
    reactions: {},
    comments: [
    ],
  },
  {
    id: '3',
    author: 'Challenge',
    date: new Date().toISOString(),
    content: 'Aujourd\'hui : 3 respirations profondes à chaque fois que vous regardez votre téléphone.',
    likes: 89,
    type: 'message',
    reactions: {},
    comments: [
    ],
  },
  {
    id: '4',
    author: 'Camille',
    date: new Date().toISOString(),
    content: 'Qui a testé le nouveau cours de Pilates ? C\'est intense pour les abdos ! 🔥',
    likes: 23,
    type: 'message',
    reactions: {},
    comments: [
    ],
  },
  {
    id: '5',
    author: 'Lucas',
    date: new Date().toISOString(),
    content: 'Petite victoire : j\'ai réussi à méditer 10 minutes ce matin sans regarder ma montre.',
    likes: 56,
    type: 'message',
    reactions: {},
    comments: [
    ],
  },
];


export const MockService = {
  getActivities: async (): Promise<Activity[]> => {
    const { data, error } = await supabase
      .from('activities')
      .select('*');

    if (error) {
      console.error('Erreur Supabase:', error.message);
      return [];
    }

    const formattedData = data.map((item) => ({
      ...item,
      dureeMinutes: item.duree_minutes,
      contentUrl: item.content_url,
      imageUrl: item.image_url, // Added this!
      couleurPrincipale: item.couleur_principale
    }));

    return formattedData as Activity[];
  },
  saveActivity: async (activity: Activity) => {
    const index = MOCK_ACTIVITIES.findIndex(a => a.id === activity.id);
    if (index >= 0) MOCK_ACTIVITIES[index] = activity;
    else MOCK_ACTIVITIES.push(activity);
  },
  deleteActivity: async (id: string) => {
    const index = MOCK_ACTIVITIES.findIndex(a => a.id === id);
    if (index >= 0) MOCK_ACTIVITIES.splice(index, 1);
  },
  toggleFavorite: async (id: string) => {
    const act = MOCK_ACTIVITIES.find(a => a.id === id);
    if (act) act.estFavori = !act.estFavori;
  },

  getProducts: async () => MOCK_PRODUCTS,
  saveProduct: async (product: Product) => {
    const index = MOCK_PRODUCTS.findIndex(p => p.id === product.id);
    if (index >= 0) MOCK_PRODUCTS[index] = product;
    else MOCK_PRODUCTS.push(product);
  },
  deleteProduct: async (id: string) => {
    const index = MOCK_PRODUCTS.findIndex(p => p.id === id);
    if (index >= 0) MOCK_PRODUCTS.splice(index, 1);
  },

  getPosts: async () => MOCK_POSTS,
  addPost: async (post: Partial<CommunityPost>) => {
    const newPost: CommunityPost = {
      id: Math.random().toString(36).substr(2, 9),
      author: post.author || 'Moi',
      content: post.content || '',
      type: post.type || 'message',
      likes: 0,
      date: new Date().toISOString(),
      comments: [],
      reactions: {}
    };
    MOCK_POSTS.unshift(newPost);
  },
  reactToPost: async (id: string, reaction: string) => {
    const post = MOCK_POSTS.find(p => p.id === id);
    if (post) {
      if (!post.reactions) post.reactions = {};
      if (post.userReaction === reaction) {
        post.reactions[reaction] = Math.max(0, (post.reactions[reaction] || 1) - 1);
        post.userReaction = null;
      } else {
        if (post.userReaction && post.reactions[post.userReaction]) {
          post.reactions[post.userReaction]--;
        }
        post.reactions[reaction] = (post.reactions[reaction] || 0) + 1;
        post.userReaction = reaction;
      }
    }
  },

  getChallenges: async () => MOCK_CHALLENGES,
  getSessions: async () => MOCK_SESSIONS,
  getNotifications: async () => MOCK_NOTIFICATIONS,
  getMoodHistory: async () => MOCK_MOOD_HISTORY,
  getQuoteOfTheDay: (): QuoteOfTheDay => MOCK_QUOTES[0] || { id: '0', texte: 'Le bonheur est parfois caché dans l\'inconnu.', auteur: 'Victor Hugo' },
  getComments: async () => [],
};